### ISSUE TITLE
CRASH WHEN START

### ISSUE THREAD

**Issue by DanteDEVS** [DanteDEVS/BedwarsLED#1]
THIS IS A COMMON THING TO HAPPEN
BEDWARS LED IS STILL IN ITS DEV STAGE
SO WHEN YOU START UP THE GAMEMODE
IT WILL CRASH
AFTER IT CRASHES 
RELOAD THE SERVER
TRY IT NOW 
IT WILL WORK FINE

**Comment by DanteDEVS** [comment]
IF YOU GET ANY OTHER PROBLEMS 
MAKE A NEW ISSUE

**Comment by llPushkarSinghll** [comment]
OK

> IF YOU GET ANY OTHER PROBLEMS MAKE A NEW ISSUE

**Comment by llPushkarSinghll** [comment]
> IF YOU GET ANY OTHER PROBLEMS MAKE A NEW ISSUE

OK

**Comment by MrDiamond64** [comment]
WHY ARE WE YELLING?

**Comment by ItsNobodyDEV** [comment]
> WHY ARE WE YELLING?

yeah why is he yelling
