### ISSUE TITLE
NPC

### ISSUE THREAD

**Issue by DanteDEVS** [DanteDEVS/BedwarsLED#2]
This is a problem 
since the npc dont really work
you can kill it 
well if you have this problem
i recommond you to download
NOPVP BY LaithDev

**Comment by Zinkil-YT** [comment]
XD

**Comment by llPushkarSinghll** [comment]
LOL

**Comment by llPushkarSinghll** [comment]
> This is a problem since the npc dont really work you can kill it well if you have this problem i recommond you to download NOPVP BY LaithDev

BETTER JUST PUT NOPVP CODE IN BEDWARS SO NO EXTERNAL PLUGINS HAVE TO BE USED

**Comment by llPushkarSinghll** [comment]
Wait wtf NoPvp plugin = No PvP In Bedwars :V , Lmao

**Comment by DanteDEVS** [comment]
DUDE NO PVP PLUGIN
YOU CAN PICK THE WORLD YOU WANT NO PVP

**Comment by llPushkarSinghll** [comment]
> DUDE NO PVP PLUGIN YOU CAN PICK THE WORLD YOU WANT NO PVP

No u idiot , if we want npc should not be killed we will put the bedwars world in config then we play match in same world, use your brain!

**Comment by ItsNobodyDEV** [comment]
> > DUDE NO PVP PLUGIN YOU CAN PICK THE WORLD YOU WANT NO PVP
> 
> No u idiot , if we want npc should not be killed we will put the bedwars world in config then we play match in same world ,players can't pvp, use your brain!

you kinda rude chill

**Comment by llPushkarSinghll** [comment]
> > > DUDE NO PVP PLUGIN YOU CAN PICK THE WORLD YOU WANT NO PVP
> > 
> > 
> > No u idiot , if we want npc should not be killed we will put the bedwars world in config then we play match in same world ,players can't pvp, use your brain!
> 
> you kinda rude chill

Bruh , i am just trying to help lol , 😂😂
