### ISSUE TITLE
/bw setbed

### ISSUE THREAD

**Issue by DanteDEVS** [DanteDEVS/BedwarsLED#4]
ok so one of my dev friends wanted this plugin so i sended the link
he said that when he used /bw setbed it gave him the intenal server error
now the reason is because he didnt put in the teams name 
/bw setbed {map} {teams name}
REMEBER USING THAT 
IM GONNA TRY TO FIX THIS ERROR

**Comment by YuriTotoso** [comment]
what's the name of the teams?
